### ISSUE TITLE
error	instance system.adapter.firetv.0 terminated with code 1 ()

### ISSUE THREAD

**Issue by BeerMacht** [soef/iobroker.firetv#1]
System is Rapi3b

Try to search devices returns:
Adapter TR-064 ist nicht gestartet, bitte starten bzw. aktivieren!
TR-064 is up and running since .20 (thanks!)

	message * system.adapter.firetv.0 _id=system.adapter.firetv.0, type=instance, name=firetv, version=0.0.14, title=Fire TV, desc=Amazon Fire TV, platform=Javascript/Node.js, keywords=[firetv, fire tv, fire-tv, amazon fire tv], mode=daemon, icon=firetv.png, extIcon=https://raw.githubusercontent.com/soef/iobroker.firetv/master/admin/firetv.png, readme=https://github.com/soef/iobroker.firetv/blob/master/README.md, loglevel=debug, type=hardware, enabled=true, messagebox=true, installedVersion=0.0.14, host=bespin, devices=[enabled=true, name=FireTV, ip=xxx.xxx.xxx.xxx], adbPath=C:\Program Files (x86)\Minimal ADB and Fastboot\adb.exe

espin	2017-01-13 20:24:26.587	error	instance system.adapter.firetv.0 terminated with code 1 ()
host.bespin	2017-01-13 20:24:25.100	info	instance system.adapter.firetv.0 started with pid 1929
host.bespin	2017-01-13 20:24:23.997	info	Restart adapter system.adapter.firetv.0 because enabled
host.bespin	2017-01-13 20:24:23.996	error	instance system.adapter.firetv.0 terminated with code 1 ()
host.bespin	2017-01-13 20:24:22.507	info	instance system.adapter.firetv.0 started with pid 1923
host.bespin	2017-01-13 20:24:16.822	info	Restart adapter system.adapter.firetv.0 because enabled
host.bespin	2017-01-13 20:24:16.821	error	instance system.adapter.firetv.0 terminated with code 1 ()
host.bespin	2017-01-13 20:24:15.383	info	instance system.adapter.firetv.0 started with pid 1917
cloud.0	2017-01-13 20:24:14.894	debug	Created ALEXA device: Alexa xxx xxx xxx xxx ['turnOn','turnOff']
cloud.0	2017-01-13 20:24:14.894	debug	Created ALEXA device: Alexa active ['turnOn','turnOff']
inMem	2017-01-13 20:24:13.868	debug	message * tr-064.0.devices.FireTV.lastActive-ts type=state, name=lastActive-ts, type=number, role=state, , _id=tr-064.0.devices.FireTV.lastActive-ts
inMem	2017-01-13 20:24:13.852	debug	message * tr-064.0.devices.FireTV.lastActive type=state, name=lastActive, type=string, role=state, , _id=tr-064.0.devices.FireTV.lastActive
inMem	2017-01-13 20:24:13.833	debug	message * tr-064.0.devices.FireTV.active type=state, name=active, type=boolean, role=state, , _id=tr-064.0.devices.FireTV.active
inMem	2017-01-13 20:24:13.811	debug	message * tr-064.0.devices.FireTV type=state, name=FireTV (192.68.178.175), type=boolean, role=channel, mac=XX:XX:XX:XX:XX:XX, _id=tr-064.0.devices.FireTV
tr-064.0	2017-01-13 20:24:11.691	info	starting. Version 0.1.20 in /opt/iobroker/node_modules/iobroker.tr-064, node: v4.7.2
host.bespin	2017-01-13 20:24:09.286	info	instance system.adapter.tr-064.0 started with pid 1907
host.bespin	2017-01-13 20:24:08.125	info	Restart adapter system.adapter.firetv.0 because enabled
host.bespin	2017-01-13 20:24:08.125	error	instance system.adapter.firetv.0 terminated with code 1 ()
host.bespin	2017-01-13 20:24:06.811	info	instance system.adapter.tr-064.0 terminated with code 0 (OK)

**Comment by GermanBluefox** [comment]
This should be not more actual, isn't it?

**Comment by soef** [comment]
I think that is history.
