### ISSUE TITLE
only Windows Adapter

### ISSUE THREAD

**Issue by simpixo** [soef/iobroker.firetv#2]
Hi soef 

Is this only a Windows Adapter!? Because on Linux do not exist EXE FILES 😕

I have installed the ADB and Fasttools but the adpter do not work

Cheers
Adrian

**Comment by soef** [comment]
Hi, did you configure the path (including filename) to the adb executable file?

**Comment by vr6syncro** [comment]
Hey same question here.

I can install abd on linux but there is no exe
How to configurate it to get it work?

**Comment by username8712** [comment]
Hi,

I installed these adapter on raspbian. I installed adb with these repository ppa:phablet-team/tools.
Then I added in settings for these adapter the path to adb (/usr/bin/adb). But searching for devices repeats "No devices found".  
Can you help?

**Comment by soef** [comment]
Are there any entries in the log? During the start of the adapter there must be at least one entry with the IP-Address and the ADB and Android Version.

**Comment by username8712** [comment]
I got only this in the log file.

firetv.0	2017-07-04 18:04:26.503	info	system.adapter.admin.0: logging true
firetv.0	2017-07-04 17:59:20.829	info	starting. Version 0.0.27 in /opt/iobroker/node_modules/iobroker.firetv, node: v6.11.0

When the path to the adb is wrong i got this:

firetv.0	2017-07-04 18:08:09.999	info	soef.changeAdapterConfig: changed
firetv.0	2017-07-04 18:08:09.813	error	adb executable not found. undefined
firetv.0	2017-07-04 18:08:09.611	info	starting. Version 0.0.27 in /opt/iobroker/node_modules/iobroker.firetv, node: v6.11.0
firetv.0	2017-07-04 18:08:02.050	info	terminating

**Comment by soef** [comment]
"error adb executable not found. undefined". The abd executable does not exist, or the adapter has no rights to see/execute it.

**Comment by username8712** [comment]
Ok, I changed my permissons for adb.
My path to adb is this:
/usr/bin/adb

When I search now for new devices, I found no devices anyway.
Logfiles says:
firetv.0 2017-07-05 19:34:26.611 info system.adapter.admin.0: logging true
firetv.0 2017-07-05 19:34:22.255 info starting. Version 0.0.27 in /opt/iobroker/node_modules/iobroker.firetv, node: v6.11.0

**Comment by soef** [comment]
Hi, i am using this adb: https://github.com/bonnyfone/adb-arm.
otherwise, you can check the command "adb devices" or "adb connect" in a shell.

**Comment by vr6syncro** [comment]
Hello,

i have installed adb and got it working in shell and can connect my devices but the adapter did not work for me.
`
firetv.0 | 2017-07-07 16:40:32.719 | error | can not connect to 192.168.2.51:5555 Error=connect ECONNREFUSED 127.0.0.1:5037
firetv.0 | 2017-07-07 16:40:32.716 | error | can not connect to 192.168.2.54 Error=connect ECONNREFUSED 127.0.0.1:5037
firetv.0 | 2017-07-07 16:40:31.770 | info | starting. Version 0.0.27 in /opt/iobroker/node_modules/iobroker.firetv, node: v4.8.2
firetv.0 | 2017-07-07 16:21:10.423 | info | terminating
`
Tryed it with ip and ip:port in the adapter config.
Device Scanner did not show any devices.

ADB Fire is working on my windows pc with both clients.
I am using Debian on my Server.
