### ISSUE TITLE
firetv => repo?

### ISSUE THREAD

**Issue by GermanBluefox** [soef/iobroker.firetv#3]
Is it so far?

**Comment by soef** [comment]
Yes, you can add the adapter to the repository.

**Comment by GermanBluefox** [comment]
Cam you Please to weite some more words about this skill. Even I do not understand, what can I do with that :)

What is adb?  And where can I get it ?

**Comment by soef** [comment]
Hi, I have extended the readme. What do you think?

**Comment by GermanBluefox** [comment]
Documentation is much better. Thanks :)
