### ISSUE TITLE
Linux no connection

### ISSUE THREAD

**Issue by vr6syncro** [soef/ioBroker.firetv#4]
Hello,

i can't get the adapter working.

I reinstalled adb on linux
tryed adb with 2 devices and it works in shell.

but i cant get the adapter to work
`
firetv.0 | 2017-07-07 16:55:44.366 | debug | Something went wrong:connect ECONNREFUSED 127.0.0.1:5037
firetv.0 | 2017-07-07 16:55:44.366 | error | can not connect to 192.168.2.51:5555 Error=connect ECONNREFUSED 127.0.0.1:5037
firetv.0 | 2017-07-07 16:55:44.365 | error | can not connect to 192.168.2.54 Error=connect ECONNREFUSED 127.0.0.1:5037
firetv.0 | 2017-07-07 16:55:44.324 | debug | FireTV: 192.168.2.54
firetv.0 | 2017-07-07 16:55:44.323 | debug | FireTV: 192.168.2.51:5555
firetv.0 | 2017-07-07 16:55:44.191 | info | starting. Version 0.0.27 in /opt/iobroker/node_modules/iobroker.firetv, node: v4.8.2
firetv.0 | 2017-07-07 16:55:40.862 | info | terminating
`
Tryed one with port and one without in the adapter config but did not help.

I dont know what to do next.
My devices working in adb fire on windows.

I am using debian on my server

**Comment by soef** [comment]
Hi, witch adb are you using? I am using this adb: https://github.com/bonnyfone/adb-arm. 
can you check in a Shell, if 
adb connect <ip of your firetv>
adb devices
runs without an error

**Comment by vr6syncro** [comment]
Hey. Using Debian apt-get ADB. It  is the  official version. In shell the device connecting and are Displayed correct. I have no  arm  i use x64

**Comment by soef** [comment]
Hi, if adb runs in a Shell, it should also run in the adapter. The error is: ECONNREFUSED. Maybe there is another process already connected or the adapter user has not the necessary rights. Can you check that?

**Comment by vr6syncro** [comment]
Hey here is my Output 
`root@FHEM:/home/alex# adb kill-server
root@FHEM:/home/alex# adb start-server
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
root@FHEM:/home/alex# adb connect 192.168.2.51:5555
connected to 192.168.2.51:5555
root@FHEM:/home/alex# adb devices
List of devices attached
192.168.2.51:5555       device

root@FHEM:/home/alex# adb disconnect 192.168.2.51:5555

root@FHEM:/home/alex# adb devices
List of devices attached

root@FHEM:/home/alex#
`

and here my iobroker output

`

firetv.0 | 2017-07-11 19:42:43.431 | error | can not connect to 192.168.2.51 Error=connect ECONNREFUSED 127.0.0.1:5037
-- | -- | -- | --
firetv.0 | 2017-07-11 19:42:43.429 | error | can not connect to 192.168.2.54 Error=connect ECONNREFUSED 127.0.0.1:5037
firetv.0 | 2017-07-11 19:42:42.503 | info | starting. Version 0.0.28 in /opt/iobroker/node_modules/iobroker.firetv, node: v4.8.2
firetv.0 | 2017-07-11 19:42:39.104 | info | terminating

`

i also updated to ur latest version today.

**Comment by vr6syncro** [comment]
still nothing

**Comment by soef** [comment]
Hi, the problem is, that the adb server did not listen on port 5037. you can check is with netstat -a 
The result is, the adapter can not connect to adb.

**Comment by vr6syncro** [comment]
Hey können ja auch deutsch schreiben. :)  dir Ports checke ich nachher ggf änder ich da was. Ich Berichte. Danke dir 

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CTJaeger** [comment]
Das gleiche Problem auch bei mir. Wie ist es zu lösen?

**Comment by Eisbaeeer** [comment]
Same issue:
 adb devices
List of devices attached
192.168.1.110:5555      device

The adapter don´t find any device.
