### ISSUE TITLE
Is still not working

### ISSUE THREAD

**Issue by vr6syncro** [soef/ioBroker.firetv#8]
Habe nun eine komplett frische ioBroker installation mit Node 6.11.3 und nun bekomme ich noch mehr fehler:

Caught | 2017-10-06 19:10:04.693 | error | by controller[0]: at bootstrap_node.js:502:3
-- | -- | -- | --
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at startup (bootstrap_node.js:149:9)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at run (bootstrap_node.js:389:7)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Module.runMain (module.js:604:10)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Function.Module._load (module.js:438:3)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at tryModuleLoad (module.js:446:12)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Module.load (module.js:487:32)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Object.Module._extensions..js (module.js:579:10)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Module._compile (module.js:570:32)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.firetv/firetv.js:6:14)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Module.require (module.js:497:17)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Function.Module._load (module.js:417:25)
Caught | 2017-10-06 19:10:04.692 | error | by controller[0]: at Function.Module._resolveFilename (module.js:469:15)
Caught | 2017-10-06 19:10:04.691 | error | by controller[0]: Error: Cannot find module './node_modules/adbkit/lib/adb/client'
Caught | 2017-10-06 19:10:04.691 | error | by controller[0]: ^
Caught | 2017-10-06 19:10:04.691 | error | by controller[0]: throw err;

**Comment by soef** [comment]
Hallo, es schein als wenn das adbkit module (./node_modules/adbkit) nicht installiert wurde. Kannst Du einmal von einer Kommandozeile in das ioBroker/node_modules/iobroker.firetv Verzeichnis wechseln und dort dann 
npm install
(ohne weiter Parameter) aufrufen. Dann müssten alle für firetv notwendigen Module installiert werden.

**Comment by vr6syncro** [comment]
Habe nun folgendes gemacht `iobroker.firetv@0.0.31 /opt/iobroker/node_modules/iobroker.firetv
├─┬ adbkit@2.11.0
│ ├── adbkit-logcat@1.1.0
│ ├─┬ adbkit-monkey@1.0.1
│ │ └── async@0.2.10
│ ├── bluebird@2.9.34
│ ├── commander@2.11.0
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── node-forge@0.7.1
│ └─┬ split@0.3.3
│   └── through@2.3.8
├── bluebird@3.5.1
├─┬ chai@4.1.2
│ ├── assertion-error@1.0.2
│ ├── check-error@1.0.2
│ ├── deep-eql@3.0.1
│ ├── get-func-name@2.0.0
│ ├── pathval@1.1.0
│ └── type-detect@4.0.3
├─┬ mdns-discovery@0.1.12
│ ├── dgram@1.0.1
│ └─┬ dns-packet@1.2.2
│   ├── ip@1.1.5
│   └── safe-buffer@5.1.1
├─┬ mocha@3.5.3
│ ├── browser-stdout@1.3.0
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├─┬ debug@2.6.8
│ │ └── ms@2.0.0
│ ├── diff@3.2.0
│ ├── escape-string-regexp@1.0.5
│ ├─┬ glob@7.1.1
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@3.0.4
│ │ │ └─┬ brace-expansion@1.1.8
│ │ │   ├── balanced-match@1.0.0
│ │ │   └── concat-map@0.0.1
│ │ ├── once@1.4.0
│ │ └── path-is-absolute@1.0.1
│ ├── growl@1.9.2
│ ├── he@1.1.1
│ ├── json3@3.3.2
│ ├─┬ lodash.create@3.1.1
│ │ ├─┬ lodash._baseassign@3.2.0
│ │ │ ├── lodash._basecopy@3.0.1
│ │ │ └─┬ lodash.keys@3.1.2
│ │ │   ├── lodash._getnative@3.9.1
│ │ │   ├── lodash.isarguments@3.1.0
│ │ │   └── lodash.isarray@3.0.4
│ │ ├── lodash._basecreate@3.0.3
│ │ └── lodash._isiterateecall@3.0.9
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └─┬ supports-color@3.1.2
│   └── has-flag@1.0.0
├─┬ path@0.12.7
│ ├── process@0.11.10
│ └── util@0.10.3
└─┬ soef@0.1.46
  ├── array-ext@0.1.5
  └── sprintf-js@1.1.1

root@ioBroker:/opt/iobroker/node_modules/iobroker.firetv# chmod 777 -R
chmod: fehlender Operand nach „777“
„chmod --help“ liefert weitere Informationen.
root@ioBroker:/opt/iobroker/node_modules/iobroker.firetv# cd^C
root@ioBroker:/opt/iobroker/node_modules/iobroker.firetv# cd /opt/iobroker/node_modules/
root@ioBroker:/opt/iobroker/node_modules# chmod 777 iobroker.firetv -R
`

bekomme nun 
`

host.ioBroker | 2017-10-10 16:57:08.759 | info | Restart adapter system.adapter.firetv.0 because enabled
-- | -- | -- | --
host.ioBroker | 2017-10-10 16:57:08.759 | error | instance system.adapter.firetv.0 terminated with code 0 (OK)
host.ioBroker | 2017-10-10 16:57:08.759 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:104:9) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
host.ioBroker | 2017-10-10 16:57:08.759 | error | Caught by controller[0]: at _combinedTickCallback (internal/process/next_tick.js:80:11)
host.ioBroker | 2017-10-10 16:57:08.759 | error | Caught by controller[0]: at emitErrorNT (net.js:1281:8)
host.ioBroker | 2017-10-10 16:57:08.759 | error | Caught by controller[0]: at Socket.emit (events.js:188:7)
host.ioBroker | 2017-10-10 16:57:08.759 | error | Caught by controller[0]: at emitOne (events.js:96:13)
host.ioBroker | 2017-10-10 16:57:08.759 | error | Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.firetv/node_modules/adbkit/lib/adb/connection.js:53:22)
host.ioBroker | 2017-10-10 16:57:08.758 | error | Caught by controller[0]: at Connection._handleError (/opt/iobroker/node_modules/iobroker.firetv/node_modules/adbkit/lib/adb/connection.js:89:12)
host.ioBroker | 2017-10-10 16:57:08.758 | error | Caught by controller[0]: at Connection.startServer (/opt/iobroker/node_modules/iobroker.firetv/node_modules/adbkit/lib/adb/connection.js:76:17)
host.ioBroker | 2017-10-10 16:57:08.758 | error | Caught by controller[0]: at Connection._exec (/opt/iobroker/node_modules/iobroker.firetv/node_modules/adbkit/lib/adb/connection.js:81:5)
host.ioBroker | 2017-10-10 16:57:08.758 | error | Caught by controller[0]: at exports.execFile (child_process.js:137:15)
host.ioBroker | 2017-10-10 16:57:08.758 | error | Caught by controller[0]: at exports.spawn (child_process.js:369:9)
host.ioBroker | 2017-10-10 16:57:08.758 | error | Caught by controller[0]: at ChildProcess.spawn (internal/child_process.js:328:11)
host.ioBroker | 2017-10-10 16:57:08.758 | error | Caught by controller[0]: at exports._errnoException (util.js:1020:11)
host.ioBroker | 2017-10-10 16:57:08.756 | error | Caught by controller[0]: { Error: spawn EACCES
firetv.0 | 2017-10-10 16:57:08.728 | error | uncaught exception: spawn EACCES

`

**Comment by soef** [comment]
Hallo, ich vermute das die ausführbare "adb" Datei nicht gefunden oder nicht ausgeführt werden kann. Ist in der Konfiguration der richtige Pfad zur adb des Packages eingetragen? Die Datei muss natürlich auch ausführbar sein.

**Comment by vr6syncro** [comment]
Habe die Datei nun an verschiedenen orten und von verschiedenen quellen probiert mit 777er rechten, der fehler bleibt

**Comment by soef** [comment]
Lässt sich in einer Shell der in der Konfiguration eingetragene Pfad (inklusive ausführbarer adb Datei) ausführen?

**Comment by vr6syncro** [comment]
Fire TV ist aus von daher ist es io das er nicht connected:
`
root@ioBroker:/opt/adb# adb connect 192.168.2.51:5555
* daemon not running. starting it now on port 5037 *
adb: malloc.c:3760: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
`

**Comment by vr6syncro** [comment]
ups..

es kommt halt wie immer der fehler `

host.ioBroker | 2017-10-18 15:21:04.778 | error | instance system.adapter.firetv.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2017-10-18 15:21:04.778 | error | by controller[0]: at bootstrap_node.js:496:3
Caught | 2017-10-18 15:21:04.778 | error | by controller[0]: at startup (bootstrap_node.js:149:9)
Caught | 2017-10-18 15:21:04.777 | error | by controller[0]: at run (bootstrap_node.js:383:7)
Caught | 2017-10-18 15:21:04.777 | error | by controller[0]: at Module.runMain (module.js:604:10)
Caught | 2017-10-18 15:21:04.777 | error | by controller[0]: at Function.Module._load (module.js:438:3)
Caught | 2017-10-18 15:21:04.777 | error | by controller[0]: at tryModuleLoad (module.js:446:12)
Caught | 2017-10-18 15:21:04.777 | error | by controller[0]: at Module.load (module.js:487:32)
Caught | 2017-10-18 15:21:04.777 | error | by controller[0]: at Object.Module._extensions..js (module.js:579:10)
Caught | 2017-10-18 15:21:04.776 | error | by controller[0]: at Module._compile (module.js:570:32)
Caught | 2017-10-18 15:21:04.776 | error | by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.firetv/firetv.js:6:14)
Caught | 2017-10-18 15:21:04.776 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2017-10-18 15:21:04.776 | error | by controller[0]: at Module.require (module.js:497:17)
Caught | 2017-10-18 15:21:04.775 | error | by controller[0]: at Function.Module._load (module.js:417:25)
Caught | 2017-10-18 15:21:04.775 | error | by controller[0]: at Function.Module._resolveFilename (module.js:469:15)
Caught | 2017-10-18 15:21:04.774 | error | by controller[0]: Error: Cannot find module './node_modules/adbkit/lib/adb/client'
Caught | 2017-10-18 15:21:04.774 | error | by controller[0]: ^
Caught | 2017-10-18 15:21:04.774 | error | by controller[0]: throw err;
Caught | 2017-10-18 15:21:04.774 | error | by controller[0]: module.js:471

`

**Comment by soef** [comment]
Error: Cannot find module './node_modules/adbkit/lib/adb/client'
Gibt es das Module unter dem angegebenen Pfad?

Zur Ausführung der adb Datei: ist denn in der Konfiguration dieser /opt/adb/adb Pfad eingetragen?

**Comment by vr6syncro** [comment]
in der firetv.js habe ich nun    Client = require('/opt/iobroker/node_modules/adbkit/lib/adb/client'), eingetragen nun geht alles.

Irgendwas stimmt dort mit dem pfad nicht.
./node_modules/adbkit/lib/adb/client' sagt er immer falscher pfad

**Comment by soef** [comment]
Das Laden der Module handhabt ja node.js native. Damit hat der Firetv-Adapter nichts zu tun.

**Comment by vr6syncro** [comment]
ja aber er nimmt ja den angegebenen pfad nicht.
muss hier ggf ./iobroker/.... rein? hab da aber keine ahnung von.

**Comment by 150d** [comment]
Der Pfad sollte relativ angegeben sein, nicht absolut: Mit

`Client = require('adbkit/lib/adb/client')`

tritt der Fehler nicht mehr auf.
